version: '3.8'

services:
  app:
    container_name: sociality-app-dev
    image: sociality-app-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
